apiVersion: v1
kind: Pod
metadata:
  labels:
    run: vault-setup
  name: vault-setup
  namespace: vault
  annotations:
    autocert.step.sm/name: vault-setup
spec:
  containers:
  - env:
    - name: PLUGIN_ACTION
      value: vault_setup
    - name: DETAILS_PATH
      value: vault/details.yml
    - name: CONFIG_PATH
      value: vault/config.yml
    - name: VAULT_CACERT
      value: /var/run/autocert.step.sm/root.crt
    - name: VAULT_ADDR
      value: https://vault-internal.vault.svc:8200
    image: registry.tiagoposse.com/cluster-droid:0.3.22
    name: vault-setup
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always