---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: drone
  name: drone-pvc
spec:
  storageClassName: "local-path-retain"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
