---
include_pipeline: templates/helm_deploy.yml
when:
  paths:
    - ingress/**/*

environment:
  PLUGIN_DETAILS_FILE: ingress/details.yml
---
include_pipeline: templates/helm_deploy.yml
when:
  paths:
    - registry/**/*

environment:
  PLUGIN_DETAILS_FILE: registry/details.yml
---
include_pipeline: certmanager/.drone.yml
when:
  paths:
    - certmanager/**/*
---
include_pipeline: templates/helm_deploy.yml
when:
  paths:
    - dashboard/**/*

environment:
  PLUGIN_DETAILS_FILE: dashboard/details.yml
---
include_pipeline: templates/helm_deploy.yml
when:
  paths:
    - museum/**/*

environment:
  PLUGIN_DETAILS_FILE: museum/details.yml
---
include_pipeline: templates/helm_deploy.yml
when:
  paths:
    - media/**/*

environment:
  PLUGIN_DETAILS_FILE: media/details.yml
---
include_pipeline: templates/helm_deploy.yml
when:
  paths:
    - dyndns/**/*

environment:
  PLUGIN_DETAILS_FILE: dyndns/details.yml
# ---
# include_pipeline: drone/.drone.yml
# when:
#   paths:
#     - drone/**/*
# ---
# include_pipeline: drone-vault/.drone.yml
# when:
#   paths:
#     - drone-vault/**/*
# ---
# include_pipeline: drone-monorepo/.drone.yml
# when:
#   paths:
#     - drone-monorepo/**/*
# ---
# include_pipeline: vault/.drone.yml
# when:
#   paths:
#     - vault/**/*