---
name: dashboard
include_pipeline: .drone.deploy.yml
environment:
  DETAILS_PATH: dashboard/details.yml

trigger:
  paths:
  - dashboard/**/*.yml
---
name: drone
include_pipeline: .drone.deploy.yml
environment:
  DETAILS_PATH: drone/details.yml

trigger:
  paths:
  - drone/**/*.yml
---
name: dyndns
include_pipeline: .drone.deploy.yml
environment:
  DETAILS_PATH: dyndns/details.yml

trigger:
  paths:
  - dyndns/**/*.yml
---
name: ingress
include_pipeline: .drone.deploy.yml
environment:
  DETAILS_PATH: ingress/details.yml

trigger:
  paths:
  - ingress/**/*.yml
---
name: museum
include_pipeline: .drone.deploy.yml
environment:
  DETAILS_PATH: museum/details.yml

trigger:
  paths:
  - museum/**/*.yml
---
name: media
include_pipeline: .drone.deploy.yml
environment:
  DETAILS_PATH: media/details.yml

trigger:
  paths:
  - media/**/*.yml
---
name: registry
include_pipeline: .drone.deploy.yml
environment:
  DETAILS_PATH: dashboard/details.yml

trigger:
  paths:
  - registry/**/*.yml
---
name: vault
include_pipeline: .drone.deploy.yml
environment:
  DETAILS_PATH: vault/details.yml

trigger:
  paths:
  - vault/**/*.yml

...