kind: pipeline
type: kubernetes

metadata:
  annotations:
    autocert.step.sm/name: drone-build
    autocert.step.sm/init-first: "true"
    autocert.step.sm/duration: "30m"
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: drone-build
    vault.hashicorp.com/agent-inject-token: "true"
    vault.hashicorp.com/agent-pre-populate-only: "true"
    vault.hashicorp.com/ca-cert: /var/run/autocert.step.sm/root.crt

platform:
  os: linux
  arch: arm64

steps:
- name: Create vault resources and deploy
  image: registry.tiagoposse.com/cluster-droid:0.5.7
  settings:
    action: upgrade
  environment:
    VAULT_TOKEN: /vault/secrets/token
    VAULT_CACERT: /var/run/autocert.step.sm/root.crt
    VAULT_ADDR: https://vault.vault.svc:8200