
replicaCount: 2

image:
  args: ['/vault/secrets/env-secrets']

fullnameOverride: drone-runner

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

## Add extra annotations to the Kubernetes runner pods here.
podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-status: injected
  vault.hashicorp.com/role: drone-runner
  vault.hashicorp.com/ca-cert: /var/run/autocert.step.sm/root.crt
  vault.hashicorp.com/agent-inject-secret-env-secrets: kv/data/drone/rpc
  vault.hashicorp.com/agent-inject-template-env-secrets: |
    {{- with secret "kv/data/drone/rpc" }}
    DRONE_RPC_SECRET={{ .Data.data.secret }}
    {{- end -}}
  autocert.step.sm/name: drone-runner.drone.svc
  autocert.step.sm/init-first: "true"
  autocert.step.sm/duration: "4380h"
rbac:
  buildNamespaces:
    - builds

env:
  DRONE_RPC_HOST: drone.drone.svc.cluster.local
  DRONE_RPC_PROTO: https
  DRONE_NAMESPACE_DEFAULT: builds
  DRONE_SERVICE_ACCOUNT_DEFAULT: drone-build-sa
  SSL_CERT_FILE: /var/run/autocert.step.sm/root.crt