
replicaCount: 2

rbac:
  buildNamespaces:
    - builds

env:
  DRONE_RPC_HOST: drone.drone.svc.cluster.local
  DRONE_RPC_PROTO: http
  DRONE_NAMESPACE_DEFAULT: builds
  DRONE_SERVICE_ACCOUNT_DEFAULT: drone-build-sa
