---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-data-pv
spec:
  storageClassName: ""
  claimRef:
    name: media-data-pvc
    namespace: media
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /nas/mediacenter/media
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: k3s.io/hostname
          operator: In
          values:
          - worker1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-config-pv
spec:
  storageClassName: ""
  claimRef:
    name: media-config-pvc
    namespace: media
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /nas/mediacenter/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: k3s.io/hostname
          operator: In
          values:
          - worker1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: media-data-pvc
spec:
  storageClassName: ""
  volumeName: media-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: media-config-pvc
spec:
  storageClassName: ""
  volumeName: media-config-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi