kind: pipeline
type: kubernetes
name: Deploy drone-monorepo

steps:
- name: Remove the placeholder resources
  image: registry.192.168.178.48.nip.io/drone-kubectl
  settings:
    server:
      from_secret: cluster_server
  commands:
    - kubectl delete po -n drone monorepo-placeholder
    - kubectl delete cm -n drone monorepo-placeholder
    - kubectl delete svc -n drone drone-monorepo

- image: pelotech/drone-helm3
  settings:
    mode: upgrade
    namespace: drone
    add_repos:
      customs: https://charts.tiagoposse.com
    chart: tposse/drone-monorepo
    chart_version: 0.1.0
    release: drone-monorepo
    values_files:
      - drone-monorepo/values.yml
    api_server:
      from_secret: cluster_server
    kube_service_account: drone-build-sa
