
image:
  repository: linuxserver/plex
  tag: latest
  pullPolicy: IfNotPresent

kubePlex:
  enabled: false

# Override this with the plex claim token from plex.tv/claim
claimToken: "claim-WYjEtnR7FKD5VZxYCzkP"

# Set the timezone of the plex server
timezone: Europe/Vienna

ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - media.tiagoposse.com
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "cluster-issuer"
  tls:
    - secretName: media-tls
      hosts:
        - media.tiagoposse.com

nodeSelector:
  beta.kubernetes.io/arch: arm64

persistence:
  transcode:
    claimName: plex-transcode
  data:
    claimName: plex-data
  config:
    claimName: plex-config
