
image:
  repository: emby/embyserver_arm64v8
  tag: latest
  pullPolicy: IfNotPresent

env:
  - name: UID
    value: "1000"
  - name: GID
    value: "1000"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/connection-proxy-header: keep-alive
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  path: /
  hosts:
    - media.tiagoposse.com
    - media.192.168.178.49.nip.io
  tls:
    - hosts:
      - media.tiagoposse.com
      secretName: media-ingress-tls

volumes:
  - name: data
    persistentVolumeClaim:
      claimName: media-data-pvc
  - name: config
    persistentVolumeClaim:
      claimName: media-config-pvc

volumeMounts:
  - name: config
    mountPath: "/config"
    subPath: "configs/emby"
  - name: data
    mountPath: "/medias"
    subPath: "medias"

resources:
  requests:
    memory: 2048Mi
    cpu: 1
  limits:
    memory: 4096Mi
    cpu: 5

nodeSelector: {}

tolerations: []

affinity: {}