apiVersion: v1
kind: ConfigMap
metadata:
  name: poststart
  metadata: vault
data:
  poststart.sh: |

      if [ "$VAULT_K8S_POD_NAME" != "vault-0" ]
      then
        echo "$VAULT_K8S_POD_NAME exiting"
        exit 0
      fi

      sleep 5

      echo "init"

      vault operator init -format=json >> /tmp/vault-init.json

      echo "Unsealing"

      UNSEAL_KEY_1=$(sed -n '10p' < /tmp/vault-init.json | cut -d '"' -f 2)
      UNSEAL_KEY_2=$(sed -n '11p' < /tmp/vault-init.json | cut -d '"' -f 2)
      UNSEAL_KEY_3=$(sed -n '12p' < /tmp/vault-init.json | cut -d '"' -f 2)

      for r in $(seq 0 $((REPLICAS-1)))
      do
        echo "Replica: $r"
        for k in $(seq 1 $THRESHOLD)
        do
          VAULT_ADDR=http://vault-$r.vault-internal.$VAULT_K8S_NAMESPACE.svc.cluster.local:8200 vault operator unseal $UNSEAL_KEY_1
          VAULT_ADDR=http://vault-$r.vault-internal.$VAULT_K8S_NAMESPACE.svc.cluster.local:8200 vault operator unseal $UNSEAL_KEY_2
          VAULT_ADDR=http://vault-$r.vault-internal.$VAULT_K8S_NAMESPACE.svc.cluster.local:8200 vault operator unseal $UNSEAL_KEY_3
        done

        sleep 10
      done