fullnameOverride: ingress

controller:
  kind: DaemonSet
  hostNetwork: true
  config:
    # hide Server header
    server-tokens: "false"
    use-forwarded-headers: "true"

  service:
    type: ClusterIP

  image:
    repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
    digest: sha256:fc650620719e460df04043512ec4af146b7d9da163616960e58aceeaf4ea5ba1
    tag: 0.33.0

  extraArgs:
    default-ssl-certificate: "ingress/tiagoposse-ingress"

rbac:
  create: true