apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certmanager
rules:
- apiGroups: ["*"]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: certmanager
  namespace: vault
subjects:
- kind: ServiceAccount
  name: certmanager
  namespace: tools
roleRef:
  kind: ClusterRole
  name: certmanager
  apiGroup: rbac.authorization.k8s.io