apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: zmallstep
  namespace: tools
spec:
  chart:
    repository: https://smallstep.github.io/helm-charts/
    name: autocert
    version: 1.12.3

    values:
      step-certificates:
        image:
          tag: 0.15.4

        ca:
          bootstrap:
            postInitHook: |
              printf '"authority": {\
                    "claims": {\
                      "minTLSCertDuration": "5m",\
                      "maxTLSCertDuration": "5000h",\
                      "defaultTLSCertDuration": "24h",\
                      "disableRenewal": false,\
                      "minHostSSHCertDuration": "5m",\
                      "maxHostSSHCertDuration": "1680h",\
                      "defaultHostSSHCertDuration": "720h",\
                      "minUserSSHCertDuration": "5m",\
                      "maxUserSSHCertDuration": "24h",\
                      "defaultUserSSHCertDuration": "16h"\
                    },' > /tmp/patch.json

              sed -i"" -E "s/\"authority\".+/$(cat /tmp/patch.json)/g" config/ca.json
              cat config/ca.json

      autocert:
        image:
          repository: registry.tiagoposse.com/controller
          tag: dev2
          pullPolicy: Always

        certLifetime: 87600h

      bootstrapper:
        image:
          repository: fastlorenzo/autocert-bootstrapper
          tag: latest
          pullPolicy: IfNotPresent

      renewer:
        image:
          repository: fastlorenzo/autocert-renewer
          tag: latest
          pullPolicy: IfNotPresent
